name: feature-pipeline-shipping

on: [push]
permissions:
  contents: read
  statuses: write
  security-events: read

jobs:
  feature-pipeline:
    if: github.ref != 'refs/heads/main'
    uses: tata-actions/workflows/.github/workflows/feature-java-pipeline.yaml@main
    with:
      project: roboshop
      component: shipping
      environment: dev
    secrets: inherit  

  dev-pipeline:
    if: github.ref == 'refs/heads/main'
    uses: tata-actions/workflows/.github/workflows/dev-java-pipeline.yaml@main
    with:
      project: roboshop
      component: shipping
      environment: dev
    secrets: inherit   
